version: 2
jobs:
  build:
    working_directory: ~/portfolio-site # directory used in the steps
    docker:
      - image: circleci/node:11.0.0
    steps:
      - checkout # check out source code in working directory
      - restore_cache: # restore dependency cache
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "./client/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: cd client && npm install

      - save_cache: # save dependencies to cache
          key: node-v1-{{ .Branch }}-{{ checksum "./client/package-lock.json" }}
          paths:
            - ./client/node_modules

      - run: cd client && npm test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
        name: Deploy Master to Heroku
        command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/warmenhoven-portfolio.git master

workflows:
  version: 2
  deployment:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
